# Generated by Django 4.2.13 on 2026-05-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('class_type', models.CharField(choices=[('live', 'Live'), ('recorded', 'Recorded'), ('chat', 'Chat-based'), ('in_person', 'In-person')], default='live', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('location', models.CharField(blank=True, help_text='Physical location for in-person classes', max_length=500, null=True)),
                ('meeting_url', models.URLField(blank=True, help_text='Zoom/Stream URL', null=True)),
                ('recording_link', models.URLField(blank=True, help_text='Recorded class URL', null=True)),
                ('max_students', models.IntegerField(blank=True, null=True)),
                ('enrolled_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Course title in Armenian', max_length=255)),
                ('description', models.TextField(help_text='Course description in Armenian')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='course_covers/')),
                ('category', models.CharField(help_text='Course category in Armenian', max_length=100)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('is_free', models.BooleanField(default=True)),
                ('subscription_required', models.BooleanField(default=False)),
                ('total_students', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
