# Generated by Django 4.2.13 on 2026-05-04 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(limit_choices_to={'role__in': ['tutor', 'teacher']}, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='courses.course'),
        ),
        migrations.AddField(
            model_name='class',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
