# Generated by Django 4.2.13 on 2026-05-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
