# Generated by Django 4.2.13 on 2026-05-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_make_schedule_fields_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price_amd',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Price in Armenian Dram (AMD). Leave blank if free.', max_digits=10, null=True),
        ),
    ]
