# Generated by Django 4.2.13 on 2026-05-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_2fa_verification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accepted_terms_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
