# Generated by Django 4.2.13 on 2026-05-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_accepted_terms_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='paypal_me_link',
            field=models.URLField(blank=True, help_text='e.g. https://paypal.me/yourname — used when Stripe is not configured', null=True),
        ),
    ]
